### ISSUE TITLE
Error rendering template

### ISSUE THREAD

**Issue by Wonko52** [kimai/DemoBundle#10]
Fresh installation: when calling up the plug-in page, the error appears: 
An exception has been thrown during the rendering of a template ("Warning: Array to string conversion").

The solution was:
Line 171 in var/plugins/DemoBundle/Resources/views/index.html.twig

`{{ value }}`
replace with
`{{ value is iterable ? value|join(', ') : value }}`

**Comment by kevinpapst** [comment]
Thanks, fixed in latest release
