### ISSUE TITLE
Error running `kimai:bundle:demo:install` on new installation

### ISSUE THREAD

**Issue by ymarkus** [kimai/DemoBundle#5]
I set kimai up by following [the documentation (development install)](https://www.kimai.org/documentation/developers.html#development-installation), and kimai (in dev environment) is working fine.

Then I cloned this repo into var/plugins. When I run `bin/console kimai:bundle:demo:install`, I get following error:
```
❯ bin/console kimai:bundle:demo:install

Starting installation of plugin: DemoBundle ...
===============================================

                                                                                                                        
 [ERROR] Failed to install database for bundle DemoBundle. Migrations configuration key "name" does not exist.
```

Commenting out the line just moves the error to `"table_name" does not exist`

**Comment by kevinpapst** [comment]
Huh, I haven't installed this bundle in ages. 

Thanks for the PR.
